leftnav:
- identifier: 2f081eee-0a87-1073-1d70-0665eba82887
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 1e0ad658-4271-b059-64ac-402248219b7c
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 92531f3e-8a3e-cee6-6fe2-59f558861eb5
  name: Instructor Insights
  url: /pages/instructor-insights/
  weight: 30
- identifier: 219f7ee1-9c20-d982-8121-324d27a385fc
  name: Flipping the Classroom
  parent: 92531f3e-8a3e-cee6-6fe2-59f558861eb5
  url: /pages/instructor-insights/flipping-the-classroom
  weight: 40
- identifier: ef5333c4-caac-4b23-3599-e89e37e52fea
  name: Mapping Measurable Outcomes
  parent: 92531f3e-8a3e-cee6-6fe2-59f558861eb5
  url: /pages/instructor-insights/mapping-measurable-outcomes
  weight: 50
- identifier: 9bd39d24-ce43-7655-9bc5-bd62b44c6e31
  name: Assessing Students through Oral Exams
  parent: 92531f3e-8a3e-cee6-6fe2-59f558861eb5
  url: /pages/instructor-insights/assessing-students-through-oral-exams
  weight: 60
- identifier: 9a0387e0-b596-f2b7-c0db-12fb8b08b819
  name: Reflecting on the Programming Projects
  parent: 92531f3e-8a3e-cee6-6fe2-59f558861eb5
  url: /pages/instructor-insights/reflecting-on-the-programming-projects
  weight: 70
- identifier: 7c33845c-200b-cb1b-3788-0b72a4f87dd5
  name: Co-Teaching the Course
  parent: 92531f3e-8a3e-cee6-6fe2-59f558861eb5
  url: /pages/instructor-insights/co-teaching-the-course
  weight: 80
- identifier: 6018b2cc-123e-d80f-52d9-19c7a1393c2e
  name: Measurable Outcome Index
  url: /pages/measurable-outcome-index
  weight: 90
- identifier: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  name: 'Unit 1: Numerical Integration of ODEs'
  url: /pages/numerical-integration-of-ordinary-differential-equations/
  weight: 100
- identifier: 223cf785-d78e-af28-f88b-913e0d5df7b1
  name: 1.1 Overview
  parent: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  url: /pages/numerical-integration-of-ordinary-differential-equations/overview2/
  weight: 110
- identifier: f239c31a-53e6-28b3-a06a-8e6fff5ed57c
  name: 1.2 Discretizing ODEs
  parent: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  url: /pages/numerical-integration-of-ordinary-differential-equations/discretizing-odes/
  weight: 120
- identifier: a3fbfbbd-e140-393b-aed5-af945a9316f9
  name: 1.3 Order of Accuracy
  parent: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  url: /pages/numerical-integration-of-ordinary-differential-equations/order-of-accuracy/
  weight: 130
- identifier: 99ee39b7-79f4-9afb-0849-103c798f1c50
  name: 1.4 Convergence
  parent: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  url: /pages/numerical-integration-of-ordinary-differential-equations/convergence/
  weight: 140
- identifier: fab29380-eb66-91e4-e3ce-4dfce3f50fbe
  name: 1.5 Zero Stability and the Dahlquist Equivalence Theorem
  parent: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  url: /pages/numerical-integration-of-ordinary-differential-equations/zero-stability-and-the-dahlquist-equivalence-theorem/
  weight: 150
- identifier: 36e637ce-d6ff-e05d-3606-0d537611ad2e
  name: 1.6 Systems of ODE's and Eigenvalue Stability
  parent: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  url: /pages/numerical-integration-of-ordinary-differential-equations/systems-of-odes-and-eigenvalue-stability/
  weight: 160
- identifier: 935324e3-1ab2-cb57-9059-0ba1f034fcd5
  name: 1.7 Stiffness and Implicit Methods
  parent: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  url: /pages/numerical-integration-of-ordinary-differential-equations/stiffness-and-implicit-methods/
  weight: 170
- identifier: 67717326-dffb-7444-5162-101fd9a9ec91
  name: 1.8 Multi-Step Methods
  parent: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  url: /pages/numerical-integration-of-ordinary-differential-equations/multi-step-methods/
  weight: 180
- identifier: c5e7e539-a82c-8e62-0c8a-e738a18f6f10
  name: 1.9 Runge-Kutta Methods
  parent: 5cae4847-c59a-a247-c767-3c0c6b0abef1
  url: /pages/numerical-integration-of-ordinary-differential-equations/runge-kutta-methods/
  weight: 190
- identifier: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  name: 'Unit 2: Numerical Methods for PDEs'
  url: /pages/numerical-methods-for-partial-differential-equations/
  weight: 200
- identifier: 83cf414c-172d-b4cc-a6f5-1749a486c94a
  name: 2.1 Overview
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/overview3/
  weight: 210
- identifier: 735249e6-5cf9-7136-d3a6-4f4d3458178c
  name: 2.2 Partial Differential Equations
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/partial-differential-equations/
  weight: 220
- identifier: 02467893-75dd-44cc-fcac-58f1a4ee9702
  name: 2.3 Introduction to Finite Difference Methods
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/introduction-to-finite-difference-methods/
  weight: 230
- identifier: c9ae23f7-07d4-0d5c-c85b-b19ebf476df0
  name: 2.4 Analysis of Finite Difference Methods
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/analysis-of-finite-difference-methods/
  weight: 240
- identifier: 3d8df8b8-2291-7094-b5a6-9893808a75cc
  name: 2.5 Introduction to Finite Volume Methods
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/introduction-to-finite-volume-methods/
  weight: 250
- identifier: ce70b6b2-dea9-62c9-1d8e-4789958e4499
  name: 2.6 Upwinding and the CFL Condition
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/upwinding-and-the-cfl-condition/
  weight: 260
- identifier: 935b6a61-8d7d-2772-6ca1-df78ee864834
  name: 2.7 Eigenvalue Stability of Finite Difference Methods
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/eigenvalue-stability-of-finite-difference-methods/
  weight: 270
- identifier: bda18124-71a5-87a7-513f-cb81480a1e18
  name: 2.8 Method of Weighted Residuals
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/method-of-weighted-residuals/
  weight: 280
- identifier: 876be530-ac05-3384-5428-281b2b3c5b68
  name: 2.9 Introduction to Finite Elements
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/introduction-to-finite-elements/
  weight: 290
- identifier: 62673265-55df-f200-dae2-644697a179db
  name: 2.10 More on Finite Element Methods
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/more-on-finite-element-methods/
  weight: 300
- identifier: c782bcc9-abb3-f6bc-c638-027dfffdc386
  name: 2.11 The Finite Element Method for Two-Dimensional Diffusion
  parent: 125c58ac-6a34-5a7c-bba8-de2d3160cb8b
  url: /pages/numerical-methods-for-partial-differential-equations/the-finite-element-method-for-two-dimensional-diffusion/
  weight: 310
- identifier: 487c3b15-ab67-d7c9-5cff-a6b147049d0c
  name: 'Unit 3: Probabilistic Methods and Optimization'
  url: /pages/probabilistic-methods-and-optimization/
  weight: 320
- identifier: 07ccb107-020a-5395-c317-7b0998f3ed49
  name: 3.1 Overview
  parent: 487c3b15-ab67-d7c9-5cff-a6b147049d0c
  url: /pages/probabilistic-methods-and-optimization/overview4/
  weight: 330
- identifier: 972a23bc-2208-f9b1-2895-30de24175e7d
  name: 3.2 Review of Probability and Statistics
  parent: 487c3b15-ab67-d7c9-5cff-a6b147049d0c
  url: /pages/probabilistic-methods-and-optimization/review-of-probability-and-statistics/
  weight: 340
- identifier: 2733fa33-374f-cb88-814c-413cb75b3483
  name: 3.3 Monte Carlo Methods
  parent: 487c3b15-ab67-d7c9-5cff-a6b147049d0c
  url: /pages/probabilistic-methods-and-optimization/monte-carlo-methods/
  weight: 350
- identifier: 74bb46fc-55cb-5dc9-1f9b-7be6791726ec
  name: 3.4 Error Estimates for the Monte Carlo Method
  parent: 487c3b15-ab67-d7c9-5cff-a6b147049d0c
  url: /pages/probabilistic-methods-and-optimization/error-estimates-for-the-monte-carlo-method/
  weight: 360
- identifier: e719ff51-42ac-62fb-c38b-4410308e2feb
  name: 3.5 Variance Reduction Techniques for the Monte Carlo Method
  parent: 487c3b15-ab67-d7c9-5cff-a6b147049d0c
  url: /pages/probabilistic-methods-and-optimization/variance-reduction-techniques-for-the-monte-carlo-method/
  weight: 370
- identifier: 6f317b0d-95c1-d32c-f178-c9fdbae632d2
  name: 3.6 Introduction to Design Optimization
  parent: 487c3b15-ab67-d7c9-5cff-a6b147049d0c
  url: /pages/probabilistic-methods-and-optimization/introduction-to-design-optimization/
  weight: 380
- identifier: 809ebf7c-44bf-b36e-8786-306747d7e32f
  name: Lecture Videos
  url: /pages/lecture-videos
  weight: 390
- identifier: 88a44a6b-ab5e-a4b6-5c5c-1379cb3476ce
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 400
- identifier: 99048963-e96c-fc63-b687-a36dcc5be4e1
  name: Homework Assignments
  url: /pages/assignments
  weight: 410
- identifier: f280d7dd-977c-7253-0f43-76c2e35fc1df
  name: Projects
  url: /pages/projects
  weight: 420
- identifier: e557ef78-084f-8ac1-fc20-05a2eb55fb95
  name: Exams
  url: /pages/exams
  weight: 430
